### ISSUE TITLE
Difficulties with running gulp build task (aws enviroment)

### ISSUE THREAD

**Issue by alouane** [binoculars/aws-lambda-ffmpeg#18] opened 2016-09-01 19:46 UTC
Hi binoculars,
Thanks for this great build tool, I'm actually having some difficulties with running gulp build task:
1-is it normal that the generated dist folder has no file inside /dist/node_modules/ ? my dist.zip file is about ~ 5ko, no libs(ffmpeg) inside it?
2-the cloud formation is stack on `Rollback in progress` -> `Rollback Completed,` I guess something is broken!
3-the aws-lambda-ffmpeg.zip is indeed uploaded to s3, but no lambda function is created

When I run gulp aws:default for the first time, I got no error
When I run gulp aws:deployStack, I got  `Stack:arn:aws:cloudformation:eu-west-1:xxxxxxx:stack/aws-lambda-ffmpeg/xxxxxx is in ROLLBACK_COMPLETE state and can not be updated`
When I run gulp aws:update, I got  `Resource Lambda does not exist for stack aws-lambda-ffmpeg`

Is there some thing that you see or notice that could trigger these errors?

cheers

**Comment by binoculars** [comment] 2016-09-01 20:18
FFmpeg should definitely be in your dist.zip file. (check with `zipinfo dist.zip`). What OS are you using to run it?

For AWS, there are no dependencies in /dist/node_modules (this is because the AWS SDK is already present in the Lambda container).

It sounds like the stack creation failed. I'd suggest opening up the console and checking the events for the aws-lambda-ffmpeg stack. That will likely tell you where the problem is.

You can't update a stack that's in state: `Rollback Completed`. You'll have to delete the stack and try again. Please let me know what the event log looks like, so we can figure out what happened. A screenshot or output from the CLI using this command `aws cloudformation describe-stack-events --stack-name aws-lambda-ffmpeg` would be very useful.

**Comment by binoculars** [comment] 2016-09-02 00:19
Unfortunately, there are a lot of issues with Windows. I couldn't find a native node module that worked well for decompressing .tar.xz files, so I was just using the native os x / linux tar command.

I recommend either using a Docker container or [Cloud9](https://c9.io/).

**Comment by alouane** [comment] 2016-09-02 10:03
Yes sure, that's what I'm planing to do. I used cron jobs temporarily for this task, but I'm looking for something more robust and cost effective. Thanks for your time
One last question if you don't mind, based on your experience, what is the best (cost effective) solution for transcoding videos for this usage:
-150 uploaded video per day
-[30s ~ 10min] for each video
-[360p ~ HD]quality
I wanted to test performance of lambda and see if can it handle it. Aws transcoder is quit expensive(I calculated around 400$ ~ 500$ /month), most of the budget is for bandwidth used by aws cloudfront

**Comment by binoculars** [comment] 2016-09-02 13:23
Cool.

Let's assume that the average video processing time is **30 seconds** on your Lambda function (probably a high estimate IMO), running at the **1,536 MB** setting--which is also tied to CPU throughput. If you had **150** videos per day (**4,500 per month**) to process. That would be **135,000 seconds per month**. You wouldn't even break the [free tier pricing limit](https://aws.amazon.com/lambda/pricing/) at **266,667 seconds per month** in this scenario. The problem with AWS Elastic Transcoder is that it really wasn't designed for this use case. If you're getting rounded up to the nearest minute, that's a huge cost when your videos are short. If you're Netflix or Amazon running long jobs to transcode movies, ET makes a lot more sense.

So far, I have never broken the free tier on Lambda.

Content delivery is a separate issue for pricing. I recommend looking at [CloudFlare with S3](https://support.cloudflare.com/hc/en-us/articles/200168926-How-do-I-use-CloudFlare-with-Amazon-s-S3-Service-), as opposed to CloudFront. I haven't tried serving video through CloudFlare, but I imagine that it will be cheaper. Please share your feedback on this. I'd be really interested in seeing what the best way to reduce the bandwidth costs are for short videos.

I think that answers the original issue, so I'll close this one out, but feel free to keep the conversation open :smiley:

**Closed by binoculars** 2016-09-02 13:23 UTC

**Comment by alouane** [comment] 2016-09-02 14:59
Yeah, it would be very cool if the processing is around 30 seconds, I will do some tests to verify
Aws transcoder is definitely not the best solution as you described
About the cdn fees, this client use around 6Tb/month, I didn't fully connect there upload app with s3, I'm still running some tests, I calculated about 600$/month of aws cloud front usage, I will use aws cdn for about a month, and will move to another solution, maybe cloudflare or jodihost(~300$) or cdnify(~300$)... [cdn calculator](http://www.cdncalc.com/) 
I will come back to you with more details about these solutions
cheers!

**Comment by alouane** [comment] 2016-09-06 20:05
Hi @binoculars ,
I haven't yet tested lambda for video transcoding, but recently I carried out some tests with ffmpeg compiled with php in a c4.large machine & the time that it took to finish the transcoding was huge! 10 mins
the tested video was about 9min (1080p) 
ffmpeg: ffmpeg -i 1080.mp4 -c:a copy -c:v libx264 -crf 20 -maxrate 400k -bufsize 1835k   480.mp4

Also a 480p (4min) took 4.5min of transcoding to a 240p

So I'm wondering how did you manage to get a transcoding opération under 30s ?

**Comment by binoculars** [comment] 2016-09-07 14:32
If you run `cat /proc/cpuinfo` in the Lambda environment, this is what you get:

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
stepping	: 4
microcode	: 0x428
cpu MHz		: 2793.344
cache size	: 25600 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm fsgsbase smep erms xsaveopt
bugs		:
bogomips	: 5586.68
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
stepping	: 4
microcode	: 0x428
cpu MHz		: 2793.344
cache size	: 25600 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm fsgsbase smep erms xsaveopt
bugs		:
bogomips	: 5586.68
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

It appears to be a C3 instance type. There are many different variables to take into account when transcoding a video
* CPU type
* Disk I/O speed
* Memory
* The input and output codecs
* The length of the video
* How the transcoding program works and was compiled

There's no straight answer on this. My use case involves short videos--less than 30 seconds in run time. Keep in mind with Lambda, you have to allow time to download and upload the video as well (it's usually trivial if going to/from S3 in the same region).

The best thing to do is just test it and see if it meets your requirements.

**Comment by alouane** [comment] 2016-09-07 14:44
mmm.. Yeah that is what I will do, it's a pain this transcoding process! I will keep you updated when I find a perfect solution
Thanks @binoculars
