### ISSUE TITLE
Error when running task aws:deployStack

### ISSUE THREAD

**Issue by ronaldvanvugt** [binoculars/aws-lambda-ffmpeg#43] opened 2017-05-14 10:12 UTC
I'm able to run gulp **aws:create-cfn-bucket** and gulp **aws:build-upload** succesfully, but when  I run **gulp aws:deployStack**, I get the error:

 TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Parameters.map (/root/aws-lambda-ffmpeg/platform/aws/gulpfile.js:134:9)
    at Array.map (native)
    at Gulp.gulp.task (/root/aws-lambda-ffmpeg/platform/aws/gulpfile.js:134:5)
    at module.exports (/root/aws-lambda-ffmpeg/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/root/aws-lambda-ffmpeg/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/root/aws-lambda-ffmpeg/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/root/aws-lambda-ffmpeg/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by ronaldvanvugt** [comment] 2017-05-14 22:03
I removed this line from ./platform/aws/gulpfile.js:

**CI ? ['ExecutionRoleManagedPolicyArn', EXECUTION_ROLE_ARN] : undefined**

and I removed the comma from this line:
 **['VideoMaxDuration', VIDEO_MAX_DURATION],**

After these changes, it works!

**Comment by binoculars** [comment] 2017-05-15 14:11
Duplicate of #33. The fIx is in develop branch, not yet merged into master. Next release, it will be there.

**Closed by binoculars** 2017-05-15 14:11 UTC
